### ISSUE TITLE
Bridge Mode: Server Error

### ISSUE THREAD

**Issue by p-rintz** [fe80Grau/ytdlp2STRM#41]
Hey there,

thanks for the great software.

Im using the most current version in Docker and am trying to use the bridge mode (so that sponsorblock works), but the application runs into the following error:

```
[download]   0.0% of   31.12MiB at  Unknown B/s ETA Unknown10.1.0.171 - - [23/Apr/2024 23:17:26] "GET /youtube/bridge/u4RMsjieSI4 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 324, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 500, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 149, in generator
    yield from gen
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 699, in generate
    line = process.stdout.read(1024)
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 27: invalid continuation byte
```

The website just displays a 500 Internal Server Error.

Thanks!

**Comment by fe80Grau** [comment]
Ty, fixed on https://github.com/fe80Grau/ytdlp2STRM/commit/c0059c83abb81d541631037385ace63f71c8f9d5 #

**Comment by p-rintz** [comment]
The error no longer appears. Thank you. Though I do seem to have the same issue as #35 does now. More over there.
