### ISSUE TITLE
BUG: "Error during container init: crons.json not a directory"

### ISSUE THREAD

**Issue by INPoppoRTUNE** [fe80Grau/ytdlp2STRM#62]
I'm unable to build a container from the docker compose, as it return the following error:
```bash
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/[...]/crons.json" to rootfs at "/opt/ytdlp2STRM/config/crons.json": mount /[...]/crons.json:/opt/ytdlp2STRM/config/crons.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 
```
It seems that for some reasons it expect a folder instead of a file.

If I try feeding it a folder instead of a file it return the following error during the container building process:
```bash
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 10, in <module>
    crons = c.config(
  File "/opt/ytdlp2STRM/clases/config/config.py", line 13, in get_config
    with open(self.config_file, "r") as file:
IsADirectoryError: [Errno 21] Is a directory: './config/crons.json'
```
where it require a file instead of a folder.

**Comment by fe80Grau** [comment]
Hi, can you share your docker-compose.yml? And make sure you are linking an existing file on your host machine

**Comment by INPoppoRTUNE** [comment]
> Hi, can you share your docker-compose.yml? And make sure you are linking an existing file on your host machine

Sorry for the late reply, I haven't had access to the PC in the past few days.
I noticed you updated the DockerHub image 8 days ago: it now compile and works correctly.

For some reasons tho I'm now unable to play the stream on my iPad through [Outplayer](https://apps.apple.com/us/app/outplayer/id1449923287), but [KMPlayer](https://apps.apple.com/us/app/kmplayer/id835776444) seems to handle it well enough. I'll dig a bit on my own, thanks for the quick fix!

**Comment by Geoff-eg** [comment]
Can this be re-looked at. I've just come across the same error.

```
IsADirectoryError: [Errno 21] Is a directory: './config/config.json'

Traceback (most recent call last):

  File "/opt/ytdlp2STRM/main.py", line 8, in <module>

    from clases.folders import folders as f

  File "/opt/ytdlp2STRM/clases/folders/folders.py", line 9, in <module>

    class folders:

  File "/opt/ytdlp2STRM/clases/folders/folders.py", line 10, in folders

    ytdlp2strm_config = c.config('./config/config.json').get_config()

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/ytdlp2STRM/clases/config/config.py", line 15, in get_config

    with open(self.config_file, "r") as file:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

IsADirectoryError: [Errno 21] Is a directory: './config/config.json'
```

.yml file here

```
---
services:
 ytdlp2strm:
    image: fe80grau/ytdlp2strm
    container_name: ytdlp2STRM
    environment:
      - AM_I_IN_A_DOCKER_CONTAINER=Yes
      - DOCKER_PORT=5005
    volumes:
      - /mnt/NFS/Jellyfin/ytdlp2strm/media:/media
      - /mnt/NFS/Jellyfin/ytdlp2strm/youtube/plugins:/opt/ytdlp2STRM/plugins/youtube/channel_list.json
      - /mnt/NFS/Jellyfin/ytdlp2strm/youtube/plugins:/opt/ytdlp2STRM/plugins/youtube/config.json
      - /mnt/NFS/Jellyfin/ytdlp2strm/config:/opt/ytdlp2STRM/config/config.json
      - /mnt/NFS/Jellyfin/ytdlp2strm/config:/opt/ytdlp2STRM/config/crons.json
      - ytdlp2strm-data:/opt/ytdlp2STRM
    ports:
      - 5005:5000
    restart: always
volumes:
  ytdlp2strm-data:
```
