### ISSUE TITLE
Can't start the app in windows

### ISSUE THREAD

**Issue by aliak74** [fe80Grau/ytdlp2STRM#86]
Hi,

I have set up everything according to the install guide for Windows.
When i run this i get these errors:: 
schtasks.exe /run /tn "ytdlp2STRM" 

```
[2024-11-21 14:04:27,811] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\ProgramData\ytdlp2STRM\ui\routes.py", line 15, in index
    crons = _ui.crons
            ^^^^^^^^^
  File "C:\ProgramData\ytdlp2STRM\ui\ui.py", line 97, in crons
    with open(self.crons_file, 'r') as file:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/crons.json'
[2024-11-21 14:05:03,734] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maise\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\ProgramData\ytdlp2STRM\ui\routes.py", line 15, in index
    crons = _ui.crons
            ^^^^^^^^^
  File "C:\ProgramData\ytdlp2STRM\ui\ui.py", line 97, in crons
    with open(self.crons_file, 'r') as file:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/crons.json'
```

**Comment by HuskyLogan** [comment]
There is a file in C:\ProgramData\ytdlp2STRM\config named crons.example.json, rename it to crons.json

**Comment by aliak74** [comment]
> There is a file in C:\ProgramData\ytdlp2STRM\config named crons.example.json, rename it to crons.json

Thanks, that did it. 🙌
