### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by xJCPMSx** [fe80Grau/ytdlp2STRM#88]
![Captura de tela de 2024-11-27 13-17-22](https://github.com/user-attachments/assets/961cbe0b-784b-47ea-9f19-6156e6205c59)
I've been trying to install it over Linux, Docker and Docker compose but i'm always getting Internal server error. What could i do?

**Comment by MegaTheLEGEND** [comment]
Same page displayed for me. Here are the logs from the docker container.

```
[2024-12-07 01:08:21,245] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ytdlp2STRM/ui/routes.py", line 15, in index
    crons = _ui.crons
            ^^^^^^^^^
  File "/opt/ytdlp2STRM/ui/ui.py", line 97, in crons
    with open(self.crons_file, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/crons.json'
```

**Comment by xJCPMSx** [comment]
Did you create a blank crontab file?

**Comment by xJCPMSx** [comment]
Did you create a blank cron file?

**Comment by fe80Grau** [comment]
Please @xJCPMSx share the console output error or something similar. You can check https://github.com/fe80Grau/ytdlp2STRM/issues/88#issuecomment-2524736274, it may be a problem related to some configuration file
